name: Build and deploy docs

on:
  push:
    branches:
      - main
  # Trigger on PRs for testing
  pull_request:
    branches:
      - main
  workflow_dispatch:

# Define jobs
jobs:
  build-docs:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
        # Step 1: Checkout the repository
      - uses: actions/checkout@v3

        # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

        # Step 3: Upgrade pip and install package dependencies
      - name: Upgrade pip & install build tools
        run: |
          python -m pip install --upgrade pip
          pip install .

        # Step 4: Install sphinx and build docs
      - name: Install dependencies
        run: |
          pip install sphinx sphinx-rtd-theme sphinx-autodoc-typehints myst-nb

      # Step 5: Copy tutorials to be rendered (docs/source/tutorials/) and download-able (docs/source/_static/tutorials/)
      - name: Copy tutorials
        run: |
          mkdir -p docs/source/tutorials
          cp -r tutorials/* docs/source/tutorials/
          mkdir -p docs/source/_static/tutorials
          cp -r tutorials/* docs/source/_static/tutorials/

        # Step 6: Build the HTML documentation
      - name: Build HTML
        run: sphinx-build -b html docs/source/ docs/_build/html

        # Step 6: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e #v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html