name: Modify new issues

# Trigger the workflow whenever a new issue is opened
on:
  issues:
    types: [opened, reopened]

# Grant permission to modify issues
permissions:
  issues: write

# Run jobs
jobs:

  # Add default label to new/reopened issues
  add-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Add label to new issue
        uses: actions-ecosystem/action-add-labels@18f1af5e3544586314bbe15c0273249c770b2daf #v1.1.3
        with:
          github_token: ${{ github.token }}
          labels: pyissm
