name: Release pyISSM

# Trigger release on push to tags starting with 'v'
on:
  pull_request:

# Define jobs
jobs:
  # Job 2: Publish Python package to PyPI and Conda
  publish_python_package:
    uses: access-nri/actions/.github/workflows/publish-python-package.yml@davide/fix-python-publish
    with:
      pypi-package: true
      conda-package: true
    secrets: inherit
    permissions:
      actions: write